#!/bin/bash

REPOS="$1"
REV="$2"

SVNLOOK=/usr/bin/svnlook
CURL=/usr/bin/curl

TESYS='http://localhost:8080/core/rest/controller/scm'

AUTHOR=$($SVNLOOK author -r "$REV" "$REPOS")
MESSAGE=$($SVNLOOK log -r "$REV" "$REPOS")
DATE=$($SVNLOOK date -r $REV /var/subversion/repo)
#yyyy-MM-dd HH:mm:ss
FORMAT_DATE=$(echo $DATE | awk '{print $1"-"$2"-"$3}' FS="-" |  sed 's/^[ \t]*//;s/[ \t]*$//' )

RESPONSE=$($CURL -s -XPUT $TESYS -H "content-type: application/json" \
	 -d "{\"message\":\"$MESSAGE\",\"author\":\"$AUTHOR\",\"repository\":\"$REPOS\",\"revision\":\"$REV\",\"date\":\"$FORMAT_DATE\"}")

if [ "$RESPONSE" != "1" ]; then
	echo "$RESPONSE" 1>&2
	exit 1
fi

exit 0
