#!/bin/bash

REPOS="$1"
TXN="$2"

SVNLOOK=/usr/bin/svnlook
CURL=/usr/bin/curl

TESYS="http://localhost:8080/tesys/rest/controller/scm"

LOCATION="svn://localhost/"

MESSAGE=$($SVNLOOK log -t "$TXN" "$REPOS")
AUTHOR=$($SVNLOOK author -t "$TXN" "$REPOS")

#Que el sistema permita el commit

IS_COMMIT_ALLOWED=$( $CURL -s -XPOST $TESYS -H "content-type: application/json" \
				-d "{\"message\":\"$MESSAGE\",\"author\":\"$AUTHOR\",\"repository\":\"$LOCATION\"}" )

if [ "$IS_COMMIT_ALLOWED" != "1" ]; then
	echo "$IS_COMMIT_ALLOWED" 1>&2
	exit 1
fi

exit 0







